# # 데이터셋에서, 훈련이 진행되지 않는 category 살펴보자

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random
import scipy.stats as stats
import seaborn as sns

In [3]:
import os

print(os.getcwd())

/Users/we/Downloads/GCS data/1108_fitting_no.csv


In [2]:
chunk = {}
data = pd.DataFrame()
for i in range(200):
    chunk[i] = pd.read_csv('part-{:05d}-5388f416-67de-468e-abbe-4806bc02e709-c000.csv'.format(i))
    data = data.append(chunk[i])

In [3]:
chunk[199]

mid  dcateCd  scateCd  mcateCd  lcateCd  userOrderCnt  \
0  9941354  4100235  3100040  2100006  1100001             2   
1  9951430  4105738  3101052  2100201  1100034             2   
2  9971943  4105738  3101052  2100201  1100034             2   
3  9975237  4100628  3100125  2100012  1100002             2   

   userFirstLastOrderPeriod  orderMeanPeriod  userRecentlyOrderPeriod  \
0                         1              1.0                        1   
1                         1              1.0                        1   
2                         1              1.0                        1   
3                        20             20.0                       20   

      alpha      beta  lambda  prob       rcp  score  
0  Infinity  Infinity     NaN   NaN  0.086538    NaN  
1  Infinity  Infinity     NaN   NaN       NaN    NaN  
2  Infinity  Infinity     NaN   NaN       NaN    NaN  
3  Infinity  Infinity     NaN   NaN  0.058824    NaN

In [4]:
data

mid    dcateCd    scateCd    mcateCd    lcateCd  userOrderCnt  \
0   10017689    4104891    3100863    2100154    1100024             2   
1   10019746    4103141    3100566    2100093    1100017             2   
2   10023760    4104481    3100803    2100144    1100023             2   
3   10048010    4105738    3101052    2100201    1100034             2   
4   10095299    4105738    3101052    2100201    1100034             2   
0   10118187    4103867    3100683    2100119    1100017             2   
1   10132208    4102468    3100454    2100077    1100013             2   
2   10188557  232040111  232040100  232040000  232000000             2   
3   10190522  235040302  235040300  235040000  235000000             4   
4   10201199    4105738    3101052    2100201    1100034             4   
0   10213742    4105740    3101054    2100202    1100035             2   
1   10231614    4103416    3100614    2100098    1100018             2   
2   10237591    4102788    3100500    2100081    1100014             2   
3    1024084    4102319    3100423    2100070    1100013             3   
4    1026853  232063601  232063600  232060000  232000000             2   
0   10293497    4103666    3100647    2100108    1100019             2   
1   10307533    4101624    3100308    2100047    1100009             3   
2   10308987    4105134    3100906    2100171    1100027             2   
3   10331407    4104684    3100836    2100151    1100024             3   
0   10337967    4105738    3101052    2100201    1100034             2   
1   10462818    4102693    3100489    2100084    1100014             2   
2   10481533    4105738    3101052    2100201    1100034             2   
3   10507275    4101707    3100325    2100051    1100010             2   
4   10550536    4100114    3100018    2100005    1100000             2   
0    1057542    4100277    3100048    2100008    1100001             2   
1    1062030    4103863    3100683    2100119    1100017             3   
2   10669752    4105738    3101052    2100201    1100034             5   
3   10704791    4101956    3100370    2100062    1100011             3   
4   10727628    4102588    3100474    2100078    1100013             2   
0   10752156    4104135    3100728    2100125    1100020             2   
..       ...        ...        ...        ...        ...           ...   
2    9383932    4105742    3101056    2100202    1100035             2   
3    9388065    4100804    3100164    2100017    1100003             2   
0    9395528    4100550    3100106    2100011    1100002             2   
1    9415158    4105738    3101052    2100201    1100034             2   
2    9419255    4105738    3101052    2100201    1100034             2   
3    9448759    4101363    3100259    2100035    1100006             2   
4    9458481    4103925    3100692    2100120    1100020             2   
0    9481163    4101820    3100347    2100057    1100010             2   
1    9494402  239030207  239030200  239030000  239000000             2   
2    9517002  233020117  233020100  233020000  233000000             2   
3    9565478    4105738    3101052    2100201    1100034             6   
4    9566435    4101685    3100322    2100050    1100009             2   
0    9580609    4102414    3100447    2100076    1100013             2   
1    9600489    4103785    3100669    2100186    1100017             2   
2    9615840    4105198    3100210    2100028    1100005             4   
3    9668619    4102362    3100434    2100073    1100013             2   
0    9675924    4105738    3101052    2100201    1100034             2   
1    9721276    4100427    3100077    2100009    1100002             2   
2    9729972    4101073    3100203    2100026    1100005             2   
3    9753047    4102338    3100428    2100072    1100013             3   
4    9753940    4102387    3100440    2100074    1100013             2   
0    9785857    4101815    3100346    2100057    1100010             2   
1    9796756 

In [17]:
data.to_csv('result.csv')

In [5]:
data.columns

Index(['mid', 'dcateCd', 'scateCd', 'mcateCd', 'lcateCd', 'userOrderCnt',
       'userFirstLastOrderPeriod', 'orderMeanPeriod',
       'userRecentlyOrderPeriod', 'alpha', 'beta', 'lambda', 'prob', 'rcp',
       'score'],
      dtype='object')

In [1]:
data.dcateCd.nunique()  # 700여개의 category가 Gamma fitting안되네

NameError: name 'data' is not defined

In [7]:
data[data.rcp > 0.25].dcateCd.nunique()  # 그중에서 rcp >0.25 인 애들이... 34개!

34

In [67]:
# Fitting X 중에, Rcp 0.3이상인것  - 27개

data[data.rcp >= 0.3].dcateCd.unique()

array([  4103863,   4104535,   4105200,   4100394,   4101592, 233090602,
         4105829,   4105426,   4101828,   4104132,   4101785,   4105660,
         4104260,   4104259,   4103230,   4105324,   4101093,   4105524,
         4102648,   4100981,   4105154,   4105647,   4100951,   4101334,
         4105447,   4101363,   4105198])

In [69]:
# Fitting X 중에, Rcp 0.25 초과인 것!

data[data.rcp > 0.25].dcateCd.unique()

array([235040302,   4103863,   4105373,   4100977,   4104535,   4105200,
         4105320,   4100394,   4104705,   4101592, 233090602,   4105829,
         4105426,   4101828,   4104132,   4101785,   4105660,   4104260,
         4104259,   4103230,   4105324,   4101043,   4101093,   4105524,
         4102648,   4100981,   4105154,   4105647,   4103231,   4100951,
         4101334,   4105447,   4101363,   4105198])

In [65]:
data[data.dcateCd == data[data.rcp > 0.25].dcateCd.unique()[6]][:1]

mid  dcateCd  scateCd  mcateCd  lcateCd  userOrderCnt  \
2  13498694  4105320  3100930  2100179  1100005             2   

   userFirstLastOrderPeriod  orderMeanPeriod  userRecentlyOrderPeriod  \
2                        17             17.0                       17   

      alpha      beta  lambda  prob       rcp  score  
2  Infinity  Infinity     NaN   NaN  0.277778    NaN

---

---

In [28]:
import tensorflow as tf

/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [31]:
sess = tf.Session()

---

## # tf.constant()

In [48]:
tensor = tf.constant([1, 2, 3, 4, 5, 6, 7])

In [46]:
print(sess.run(tensor))

[1 2 3 4 5 6 7]


In [47]:
sess.run(tensor).shape

(7,)

---

In [35]:
tensor = tf.constant([[1, 2, 3, 4, 5, 6, 7]])

In [36]:
print(sess.run(tensor))

[[1 2 3 4 5 6 7]]


In [37]:
sess.run(tensor).shape

(1, 7)

---

In [42]:
tensor = tf.constant([[1], [2], [3], [4], [5], [6], [7]])

In [43]:
print(sess.run(tensor))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


In [44]:
sess.run(tensor).shape

(7, 1)

## # tf.linspace()

In [54]:
lin = tf.linspace(10.0, 15.0, num = 6, name = 'linspace')

In [56]:
x = sess.run(lin)

In [57]:
x

array([10., 11., 12., 13., 14., 15.], dtype=float32)

---

In [62]:
y = np.arange(10)

In [63]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])